GameData = {["save_version"] = 1, ["language"] = 1, ["network"] = 1, ["networkMax"] = 7, ["overflow"] = 0, ["seed"] = 16746, ["new_enemies"] = 0, ["new_missions"] = 0, ["new_equip"] = 1, ["difficulty"] = 1, ["new_abilities"] = 1, ["ach_info"] = {["squad"] = "Archive_A", ["trackers"] = {["Detritus_B_2"] = 0, ["Global_Challenge_Power"] = 18, ["Archive_A_1"] = 0, ["Archive_B_2"] = 0, ["Rust_A_2"] = 0, ["Rust_A_3"] = 0, ["Pinnacle_A_3"] = 0, ["Archive_B_1"] = 0, ["Pinnacle_B_3"] = 0, ["Detritus_B_1"] = 0, ["Pinnacle_B_1"] = 0, ["Global_Island_Mechs"] = 6, ["Global_Island_Building"] = 5, ["Squad_Mist_1"] = 0, ["Squad_Bomber_2"] = 0, ["Squad_Spiders_1"] = 0, ["Squad_Mist_2"] = 0, ["Squad_Heat_1"] = 0, ["Squad_Cataclysm_1"] = 0, ["Squad_Cataclysm_2"] = 0, ["Squad_Cataclysm_3"] = 0, },
},


["current"] = {["score"] = 8742, ["time"] = 3575591.750000, ["kills"] = 77, ["damage"] = 0, ["failures"] = 2, ["difficulty"] = 1, ["victory"] = false, ["islands"] = 2, ["squad"] = 0, 
["mechs"] = {"PunchMech", "TankMech", "ArtiMech", },
["colors"] = {0, 0, 0, },
["weapons"] = {"Prime_Punchmech", "Prime_Lightning", "Brute_Tankmech", "", "Ranged_Artillerymech_A", "", },
["pilot0"] = {["id"] = "Pilot_Chemical", ["name"] = "Morgan Lejeune", ["name_id"] = "Pilot_Chemical_Name", ["renamed"] = false, ["skill1"] = 7, ["skill2"] = 2, ["exp"] = 17, ["level"] = 2, ["travel"] = 0, ["final"] = 1, ["starting"] = false, },
["pilot1"] = {["id"] = "Pilot_Detritus", ["name"] = "Omar Smith", ["name_id"] = "", ["renamed"] = false, ["skill1"] = 3, ["skill2"] = 6, ["exp"] = 32, ["level"] = 1, ["travel"] = 0, ["final"] = 1, ["starting"] = true, },
["pilot2"] = {["id"] = "Pilot_Artificial", ["name"] = "A.I. Unit", ["name_id"] = "Pilot_Artificial_Name", ["renamed"] = false, ["skill1"] = 3, ["skill2"] = 0, ["exp"] = 0, ["level"] = 0, ["travel"] = 0, ["final"] = 0, ["starting"] = false, },
},
["current_squad"] = 0, ["undosave"] = true, }
 

RegionData = {
["sector"] = 2, ["island"] = -1, ["secret"] = true, 
["island0"] = {["corporation"] = "Corp_Grass", ["id"] = 0, ["secured"] = true, },
["island1"] = {["corporation"] = "Corp_Desert", ["id"] = 1, ["secured"] = true, },
["island2"] = {["corporation"] = "Corp_Snow", ["id"] = 2, ["secured"] = false, },
["island3"] = {["corporation"] = "Corp_Factory", ["id"] = 3, ["secured"] = false, },
["iBattleRegion"] = 20, 
["final_region"] = {["mission"] = "Mission0", ["player"] = {["battle_type"] = 3, ["iCurrentTurn"] = 3, ["iTeamTurn"] = 1, ["iState"] = 0, ["sMission"] = "Mission0", ["iMissionType"] = 1, ["sBriefingMessage"] = "Final_Mission_Briefing", ["podReward"] = CreateEffect({}), ["secret"] = false, ["spawn_needed"] = false, ["env_time"] = 1000, ["actions"] = 0, ["iUndoTurn"] = 1, ["aiState"] = 3, ["aiDelay"] = 0.000000, ["aiSeed"] = 30400, ["victory"] = 2, ["undo_pawns"] = {},


["map_data"] = {["version"] = 7, ["dimensions"] = Point( 8, 8 ), ["name"] = "caveAE4", ["enemy_kills"] = 3, 
["map"] = {{["loc"] = Point( 0, 0 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 0, 1 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 0, 7 ), ["terrain"] = 4, },
{["loc"] = Point( 1, 0 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 1, 1 ), ["terrain"] = 4, },
{["loc"] = Point( 1, 2 ), ["terrain"] = 0, },
{["loc"] = Point( 1, 4 ), ["terrain"] = 0, ["undo_state"] = {["active"] = true, },
},
{["loc"] = Point( 1, 5 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, ["health_min"] = 1, },
{["loc"] = Point( 1, 7 ), ["terrain"] = 4, },
{["loc"] = Point( 2, 1 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 2, 2 ), ["terrain"] = 0, ["undo_state"] = {["active"] = true, ["neighbor1"] = {["health"] = 3, ["max_health"] = 3, },
["neighbor2"] = {["health"] = 5, ["max_health"] = 5, },
},
},
{["loc"] = Point( 2, 3 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 2, 5 ), ["terrain"] = 3, ["lava"] = true, ["undo_state"] = {["active"] = true, ["neighbor0"] = {["health"] = 3, ["max_health"] = 3, },
["neighbor1"] = {["health"] = 3, ["max_health"] = 3, },
},
},
{["loc"] = Point( 3, 1 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 3, 2 ), ["terrain"] = 0, },
{["loc"] = Point( 3, 3 ), ["terrain"] = 0, },
{["loc"] = Point( 3, 5 ), ["terrain"] = 3, ["lava"] = true, ["undo_state"] = {["active"] = true, ["neighbor0"] = {["health"] = 2, ["max_health"] = 2, },
["neighbor1"] = {["health"] = 1, ["max_health"] = 3, },
["neighbor3"] = {["health"] = 3, ["max_health"] = 3, },
},
},
{["loc"] = Point( 3, 6 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 3, 7 ), ["terrain"] = 4, },
{["loc"] = Point( 4, 4 ), ["terrain"] = 0, ["undo_state"] = {["active"] = true, ["neighbor2"] = {["bOnFire"] = true, ["health"] = 4, ["max_health"] = 6, },
},
},
{["loc"] = Point( 4, 5 ), ["terrain"] = 0, ["fire"] = 1, },
{["loc"] = Point( 4, 6 ), ["terrain"] = 4, ["health_max"] = 2, ["health_min"] = 1, },
{["loc"] = Point( 4, 7 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 5, 1 ), ["terrain"] = 0, },
{["loc"] = Point( 5, 2 ), ["terrain"] = 0, },
{["loc"] = Point( 5, 3 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 5, 4 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, ["health_min"] = 1, },
{["loc"] = Point( 5, 5 ), ["terrain"] = 0, },
{["loc"] = Point( 5, 6 ), ["terrain"] = 0, },
{["loc"] = Point( 6, 1 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, ["health_min"] = 1, },
{["loc"] = Point( 6, 3 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 6, 4 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 6, 6 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 7, 3 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 7, 4 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 7, 5 ), ["terrain"] = 3, ["lava"] = true, },
},
["cave_tiles"] = {["0"] = {["id"] = "top_L", ["cracked"] = false, ["tentacle"] = false, },
["1"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = true, },
["2"] = {["id"] = "3", ["cracked"] = true, ["tentacle"] = false, },
["3"] = {["id"] = "1", ["cracked"] = false, ["tentacle"] = false, },
["4"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = true, },
["5"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = false, },
["6"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = true, },
["7"] = {["id"] = "end", ["cracked"] = false, ["tentacle"] = false, },
["8"] = {["id"] = "top_R", ["cracked"] = false, ["tentacle"] = false, },
["9"] = {["id"] = "1", ["cracked"] = false, ["tentacle"] = false, },
["10"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = false, },
["11"] = {["id"] = "3", ["cracked"] = true, ["tentacle"] = false, },
["12"] = {["id"] = "1", ["cracked"] = false, ["tentacle"] = true, },
["13"] = {["id"] = "1", ["cracked"] = false, ["tentacle"] = false, },
["14"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = false, },
["15"] = {["id"] = "end", ["cracked"] = false, ["tentacle"] = false, },
},
["spawns"] = {"Scarab1", },
["spawn_ids"] = {147, },
["spawn_points"] = {Point(4,2), },
["zones"] = {["pylons"] = {Point( 1, 5 ), Point( 5, 4 ), Point( 5, 3 ), Point( 6, 1 ), Point( 3, 1 ), Point( 2, 1 ), Point( 6, 6 ), },
["mountain"] = {Point( 7, 5 ), Point( 7, 4 ), Point( 1, 0 ), },
["layer"] = {},
["bomb"] = {Point( 3, 3 ), Point( 3, 4 ), Point( 2, 3 ), },
["deployment"] = {Point( 3, 3 ), Point( 3, 4 ), Point( 2, 4 ), Point( 2, 3 ), },
["enemy"] = {Point( 6, 5 ), Point( 5, 1 ), Point( 5, 2 ), Point( 4, 0 ), Point( 5, 0 ), Point( 3, 0 ), Point( 5, 6 ), Point( 5, 5 ), Point( 4, 5 ), Point( 6, 2 ), Point( 4, 1 ), Point( 2, 6 ), Point( 4, 2 ), Point( 4, 3 ), Point( 4, 4 ), },
},
["tags"] = {"final_cave", "volcano", },


["pawn1"] = {["type"] = "PunchMech", ["name"] = "", ["id"] = 0, ["mech"] = true, ["offset"] = 0, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 1, ["iBonusPower"] = 0, ["iUsedBonus"] = 0, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {0, },
["healthPower"] = {0, },
["primary"] = "Prime_Punchmech", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {0, 0, },
["primary_mod2"] = {0, 0, 0, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["secondary"] = "Prime_Lightning", ["secondary_power"] = {1, },
["secondary_power_class"] = false, ["secondary_mod1"] = {0, },
["secondary_mod2"] = {0, 0, 0, },
["secondary_damaged"] = false, ["secondary_starting"] = true, ["secondary_uses"] = 1, ["pilot"] = {["id"] = "Pilot_Chemical", ["name"] = "Morgan Lejeune", ["name_id"] = "Pilot_Chemical_Name", ["renamed"] = false, ["skill1"] = 7, ["skill2"] = 2, ["exp"] = 17, ["level"] = 2, ["travel"] = 0, ["final"] = 1, ["starting"] = false, },
["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 1, ["is_corpse"] = true, ["bBoosted"] = true, ["health"] = 3, ["max_health"] = 3, ["undo_state"] = {["health"] = 3, ["max_health"] = 3, },
["undo_ready"] = false, ["undo_point"] = Point(4,4), ["iMissionDamage"] = 0, ["location"] = Point(4,4), ["last_location"] = Point(3,4), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 3, ["iTurnsRemaining"] = 2, ["undoPosition"] = Point(4,4), ["undoReady"] = false, ["iKillCount"] = 4, ["iOwner"] = 0, ["piTarget"] = Point(4,5), ["piOrigin"] = Point(4,4), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(4,5), },


["pawn2"] = {["type"] = "TankMech", ["name"] = "", ["id"] = 1, ["mech"] = true, ["offset"] = 0, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 0, ["iBonusPower"] = 0, ["iUsedBonus"] = 1, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {0, },
["healthPower"] = {2, },
["primary"] = "Brute_Tankmech", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {0, 0, },
["primary_mod2"] = {0, 0, 0, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["pilot"] = {["id"] = "Pilot_Detritus", ["name"] = "Omar Smith", ["name_id"] = "", ["renamed"] = false, ["skill1"] = 3, ["skill2"] = 6, ["exp"] = 32, ["level"] = 1, ["travel"] = 0, ["final"] = 1, ["starting"] = true, },
["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = true, ["health"] = 5, ["max_health"] = 5, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(2,2), ["iMissionDamage"] = 0, ["location"] = Point(2,2), ["last_location"] = Point(2,3), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 3, ["iTurnsRemaining"] = 2, ["undoPosition"] = Point(2,2), ["undoReady"] = false, ["iKillCount"] = 3, ["iOwner"] = 1, ["piTarget"] = Point(3,2), ["piOrigin"] = Point(2,2), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(3,2), },


["pawn3"] = {["type"] = "ArtiMech", ["name"] = "", ["id"] = 2, ["mech"] = true, ["offset"] = 0, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 1, ["iBonusPower"] = 0, ["iUsedBonus"] = 0, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {0, },
["healthPower"] = {0, },
["primary"] = "Ranged_Artillerymech", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {1, },
["primary_mod2"] = {0, 0, 0, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 1, ["is_corpse"] = true, ["health"] = 1, ["max_health"] = 2, ["undo_state"] = {["health"] = 1, ["max_health"] = 2, },
["undo_ready"] = false, ["undo_point"] = Point(1,4), ["iMissionDamage"] = 0, ["location"] = Point(1,4), ["last_location"] = Point(2,4), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 3, ["iTurnsRemaining"] = 2, ["undoPosition"] = Point(1,4), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 2, ["piTarget"] = Point(4,4), ["piOrigin"] = Point(1,4), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(4,4), },


["pawn4"] = {["type"] = "BeetleBoss", ["name"] = "", ["id"] = 116, ["mech"] = false, ["offset"] = 2, ["primary"] = "BeetleAtkB", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["bOnFire"] = true, ["health"] = 1, ["max_health"] = 6, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(5,5), ["last_location"] = Point(4,5), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 3, ["iTurnsRemaining"] = 3, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 116, ["piTarget"] = Point(5,4), ["piOrigin"] = Point(5,5), ["piQueuedShot"] = Point(5,4), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(5,4), },


["pawn5"] = {["type"] = "Hornet1", ["name"] = "", ["id"] = 117, ["mech"] = false, ["offset"] = 0, ["primary"] = "HornetAtk1", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 1, ["max_health"] = 2, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(1,2), ["last_location"] = Point(1,3), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 3, ["iTurnsRemaining"] = 3, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 117, ["piTarget"] = Point(2,2), ["piOrigin"] = Point(1,2), ["piQueuedShot"] = Point(2,2), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(2,2), },


["pawn6"] = {["type"] = "Hornet1", ["name"] = "", ["id"] = 118, ["mech"] = false, ["offset"] = 0, ["primary"] = "HornetAtk1", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 2, ["max_health"] = 2, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(5,6), ["last_location"] = Point(5,5), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 3, ["iTurnsRemaining"] = 3, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 118, ["piTarget"] = Point(6,6), ["piOrigin"] = Point(5,6), ["piQueuedShot"] = Point(6,6), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(6,6), },


["pawn7"] = {["type"] = "Firefly1", ["name"] = "", ["id"] = 122, ["mech"] = false, ["offset"] = 0, ["primary"] = "FireflyAtk1", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 1, ["max_health"] = 3, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(3,2), ["last_location"] = Point(3,2), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 1, ["iTurnsRemaining"] = 3, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 122, ["piTarget"] = Point(3,1), ["piOrigin"] = Point(3,2), ["piQueuedShot"] = Point(3,1), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(3,1), },


["pawn8"] = {["type"] = "Hornet1", ["name"] = "", ["id"] = 123, ["mech"] = false, ["offset"] = 0, ["primary"] = "HornetAtk1", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 1, ["max_health"] = 2, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(5,1), ["last_location"] = Point(4,1), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 1, ["iTurnsRemaining"] = 3, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 123, ["piTarget"] = Point(6,1), ["piOrigin"] = Point(5,1), ["piQueuedShot"] = Point(6,1), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(6,1), },


["pawn9"] = {["type"] = "Firefly2", ["name"] = "", ["id"] = 142, ["mech"] = false, ["offset"] = 1, ["primary"] = "FireflyAtk2", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 5, ["max_health"] = 5, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(5,2), ["last_location"] = Point(5,2), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 0, ["iTurnsRemaining"] = -1263184415, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 142, ["piTarget"] = Point(5,3), ["piOrigin"] = Point(5,2), ["piQueuedShot"] = Point(5,3), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(5,3), },


["pawn10"] = {["type"] = "BigBomb", ["name"] = "", ["id"] = 120, ["mech"] = false, ["offset"] = 0, ["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 3, ["max_health"] = 4, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(3,3), ["last_location"] = Point(3,3), ["iCurrentWeapon"] = 0, ["iTurnCount"] = 3, ["iTurnsRemaining"] = 2, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 120, ["piTarget"] = Point(-1,-1), ["piOrigin"] = Point(-1,-1), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(-1,-1), },
["pawn_count"] = 10, ["blocked_points"] = {Point(1,5), Point(2,1), Point(3,1), Point(5,3), Point(5,4), Point(6,1), Point(6,6), },
["blocked_type"] = {2, 2, 2, 2, 2, 2, 2, },
},


},
["state"] = 1, ["name"] = "Volcanic Hive", },
}
 

GAME = { 
["WeaponDeck"] = { 
[31] = "Ranged_ScatterShot", 
[2] = "Prime_ShieldBash", 
[8] = "Prime_Areablast", 
[32] = "Ranged_BackShot", 
[33] = "Ranged_Ice", 
[34] = "Ranged_SmokeBlast", 
[35] = "Ranged_Fireball", 
[9] = "Prime_Spear", 
[36] = "Ranged_RainingVolley", 
[37] = "Ranged_Wide", 
[38] = "Ranged_Dual", 
[39] = "Science_Pullmech", 
[10] = "Prime_Leap", 
[40] = "Science_Gravwell", 
[41] = "Science_Swap", 
[42] = "Science_Repulse", 
[43] = "Science_AcidShot", 
[11] = "Prime_SpinFist", 
[44] = "Science_Confuse", 
[45] = "Science_SmokeDefense", 
[46] = "Science_Shield", 
[47] = "Science_FireBeam", 
[12] = "Prime_Sword", 
[48] = "Science_FreezeBeam", 
[49] = "Science_LocalShield", 
[50] = "Science_PushBeam", 
[51] = "Support_Boosters", 
[13] = "Prime_Smash", 
[52] = "Support_Smoke", 
[3] = "Prime_Rockmech", 
[53] = "Support_Refrigerate", 
[4] = "Prime_RightHook", 
[54] = "Support_Destruct", 
[75] = "Prime_PrismLaser", 
[55] = "DeploySkill_ShieldTank", 
[14] = "Brute_Jetmech", 
[56] = "DeploySkill_Tank", 
[78] = "Prime_TC_Feint", 
[57] = "DeploySkill_AcidTank", 
[79] = "Prime_KO_Crack", 
[58] = "DeploySkill_PullTank", 
[83] = "Brute_TC_GuidedMissile", 
[59] = "Support_Force", 
[15] = "Brute_Mirrorshot", 
[60] = "Support_Blizzard", 
[24] = "Brute_Splitshot", 
[61] = "Passive_FlameImmune", 
[7] = "Prime_Flamethrower", 
[62] = "Passive_Electric", 
[1] = "Prime_Lasermech", 
[63] = "Passive_Leech", 
[16] = "Brute_PhaseShot", 
[64] = "Passive_MassRepair", 
[65] = "Passive_Defenses", 
[66] = "Passive_Burrows", 
[17] = "Brute_Grapple", 
[68] = "Passive_Psions", 
[69] = "Passive_Boosters", 
[70] = "Passive_Medical", 
[18] = "Brute_Shrapnel", 
[72] = "Passive_ForceAmp", 
[73] = "Passive_CritDefense", 
[74] = "Prime_WayTooBig", 
[19] = "Brute_Sniper", 
[76] = "Prime_TC_Punt", 
[77] = "Prime_TC_BendBeam", 
[5] = "Prime_RocketPunch", 
[20] = "Brute_Shockblast", 
[80] = "Brute_KickBack", 
[81] = "Brute_Fracture", 
[82] = "Brute_PierceShot", 
[21] = "Brute_Beetle", 
[84] = "Brute_TC_Ricochet", 
[85] = "Brute_TC_DoubleShot", 
[86] = "Brute_KO_Combo", 
[22] = "Brute_Unstable", 
[88] = "Ranged_DeployBomb", 
[89] = "Ranged_Arachnoid", 
[90] = "Ranged_SmokeFire", 
[23] = "Brute_Heavyrocket", 
[92] = "Ranged_TC_DoubleArt", 
[93] = "Ranged_KO_Combo", 
[6] = "Prime_Shift", 
[95] = "Science_MassShift", 
[96] = "Science_TelePush", 
[97] = "Science_Placer", 
[98] = "Science_TC_Control", 
[99] = "Science_TC_Enrage", 
[100] = "Science_TC_SwapOther", 
[101] = "Science_KO_Crack", 
[102] = "Support_Confuse", 
[103] = "Support_GridDefense", 
[104] = "Support_TC_GridAtk", 
[105] = "Support_TC_Bombline", 
[106] = "Support_KO_GridCharger", 
[107] = "Passive_HealingSmoke", 
[108] = "Passive_FireBoost", 
[109] = "Passive_PlayerTurnShield", 
[110] = "Passive_VoidShock", 
[28] = "Ranged_Defensestrike", 
[27] = "Ranged_Rockthrow", 
[26] = "Brute_Sonic", 
[25] = "Brute_Bombrun", 
[29] = "Ranged_Rocket", 
[94] = "Science_RainingFire", 
[91] = "Ranged_TC_BounceShot", 
[87] = "Ranged_Crack", 
[30] = "Ranged_Ignite", 
[71] = "Passive_FriendlyFire", 
[67] = "Passive_AutoShields" 
}, 
["PodWeaponDeck"] = { 
[31] = "DeploySkill_AcidTank", 
[2] = "Prime_Spear", 
[8] = "Brute_Sniper", 
[32] = "DeploySkill_PullTank", 
[33] = "Support_Force", 
[34] = "Support_Blizzard", 
[35] = "Passive_FlameImmune", 
[9] = "Brute_Shockblast", 
[36] = "Passive_Electric", 
[37] = "Passive_Leech", 
[38] = "Passive_MassRepair", 
[39] = "Passive_Defenses", 
[10] = "Brute_Beetle", 
[40] = "Passive_Burrows", 
[41] = "Passive_AutoShields", 
[42] = "Passive_Psions", 
[43] = "Passive_Boosters", 
[11] = "Brute_Heavyrocket", 
[44] = "Passive_Medical", 
[45] = "Passive_FriendlyFire", 
[46] = "Passive_ForceAmp", 
[3] = "Prime_Leap", 
[12] = "Brute_Bombrun", 
[48] = "Prime_WayTooBig", 
[49] = "Prime_PrismLaser", 
[50] = "Prime_TC_BendBeam", 
[51] = "Prime_TC_Feint", 
[13] = "Brute_Sonic", 
[52] = "Brute_Fracture", 
[53] = "Brute_TC_GuidedMissile", 
[54] = "Brute_KO_Combo", 
[55] = "Ranged_TC_BounceShot", 
[14] = "Ranged_Ice", 
[56] = "Ranged_TC_DoubleArt", 
[57] = "Ranged_KO_Combo", 
[58] = "Science_TelePush", 
[59] = "Science_Placer", 
[15] = "Ranged_SmokeBlast", 
[60] = "Science_TC_Enrage", 
[61] = "Support_Confuse", 
[62] = "Support_GridDefense", 
[1] = "Prime_Areablast", 
[4] = "Prime_SpinFist", 
[16] = "Ranged_Fireball", 
[64] = "Support_TC_Bombline", 
[65] = "Support_KO_GridCharger", 
[66] = "Passive_HealingSmoke", 
[17] = "Ranged_RainingVolley", 
[68] = "Passive_PlayerTurnShield", 
[69] = "Passive_VoidShock", 
[18] = "Ranged_Dual", 
[19] = "Science_SmokeDefense", 
[5] = "Prime_Sword", 
[20] = "Science_Shield", 
[21] = "Science_FireBeam", 
[22] = "Science_FreezeBeam", 
[23] = "Science_LocalShield", 
[6] = "Prime_Smash", 
[24] = "Science_PushBeam", 
[25] = "Support_Boosters", 
[26] = "Support_Smoke", 
[27] = "Support_Refrigerate", 
[7] = "Brute_Grapple", 
[28] = "Support_Destruct", 
[29] = "DeploySkill_ShieldTank", 
[47] = "Passive_CritDefense", 
[30] = "DeploySkill_Tank", 
[63] = "Support_TC_GridAtk", 
[67] = "Passive_FireBoost" 
}, 
["PilotDeck"] = { 
[13] = "Pilot_Arrogant", 
[7] = "Pilot_Genius", 
[1] = "Pilot_Original", 
[2] = "Pilot_Soldier", 
[4] = "Pilot_Warrior", 
[8] = "Pilot_Miner", 
[9] = "Pilot_Recycler", 
[5] = "Pilot_Aquatic", 
[10] = "Pilot_Assassin", 
[14] = "Pilot_Delusional", 
[3] = "Pilot_Youth", 
[6] = "Pilot_Hotshot", 
[12] = "Pilot_Repairman", 
[11] = "Pilot_Leader" 
}, 
["SeenPilots"] = { 
[6] = "Pilot_Caretaker", 
[2] = "Pilot_Detritus", 
[3] = "Pilot_Rust", 
[1] = "Pilot_Archive", 
[4] = "Pilot_Medic", 
[5] = "Pilot_Chemical" 
}, 
["PodDeck"] = { 
[6] = { 
["cores"] = 1, 
["weapon"] = "random" 
}, 
[7] = { 
["cores"] = 1, 
["weapon"] = "random" 
}, 
[8] = { 
["cores"] = 1, 
["pilot"] = "random" 
}, 
[3] = { 
["cores"] = 1 
}, 
[1] = { 
["cores"] = 1 
}, 
[4] = { 
["cores"] = 1, 
["weapon"] = "random" 
}, 
[5] = { 
["cores"] = 1, 
["weapon"] = "random" 
}, 
[2] = { 
["cores"] = 1 
} 
}, 
["Bosses"] = { 
[1] = "Mission_FireflyBoss", 
[2] = "Mission_BlobBoss", 
[4] = "Mission_JellyBoss", 
[3] = "Mission_BotBoss" 
}, 
["Island"] = 2, 
["Missions"] = { 
[0] = { 
["Spawner"] = { 
["pawn_counts"] = { 
["Crab"] = 1, 
["Scarab"] = 1, 
["Scorpion"] = 3, 
["Firefly"] = 2, 
["Hornet"] = 3, 
["Leaper"] = 2, 
["Jelly_Lava"] = 1 
}, 
["used_bosses"] = 0, 
["spawn_island"] = 5, 
["curr_weakRatio"] = { 
[1] = 0, 
[2] = 1 
}, 
["num_bosses"] = 0, 
["curr_upgradeRatio"] = { 
[1] = 1, 
[2] = 1 
}, 
["num_spawns"] = 9, 
["upgrade_streak"] = 0 
}, 
["LiveEnvironment"] = { 
["Locations"] = { 
[1] = Point( 2, 5 ), 
[2] = Point( 3, 5 ), 
[3] = Point( 3, 6 ), 
[4] = Point( 3, 4 ), 
[5] = Point( 2, 6 ), 
[6] = Point( 2, 4 ) 
}, 
["LavaPath"] = { 
[7] = Point( 2, 2 ), 
[1] = Point( 3, 7 ), 
[2] = Point( 2, 7 ), 
[4] = Point( 2, 5 ), 
[8] = Point( 2, 1 ), 
[9] = Point( 2, 0 ), 
[5] = Point( 2, 4 ), 
[3] = Point( 2, 6 ), 
[6] = Point( 2, 3 ) 
}, 
["Instant"] = true, 
["EndEffect"] = true, 
["Planned"] = { 
[1] = Point( 2, 5 ), 
[2] = Point( 3, 5 ), 
[3] = Point( 3, 6 ), 
[4] = Point( 3, 4 ), 
[5] = Point( 2, 6 ), 
[6] = Point( 2, 4 ) 
}, 
["Phase"] = 3, 
["Mode"] = 1, 
["StartEffect"] = true, 
["WaterTarget"] = true 
}, 
["ID"] = "Mission_Final_Cave", 
["VoiceEvents"] = { 
}, 
["BonusObjs"] = { 
} 
} 
}, 
["Enemies"] = { 
[1] = { 
[6] = "Crab", 
[2] = "Hornet", 
[3] = "Scorpion", 
[1] = "Firefly", 
[4] = "Jelly_Health", 
[5] = "Blobber", 
["island"] = 1 
}, 
[2] = { 
[6] = "Blobber", 
[2] = "Scorpion", 
[3] = "Firefly", 
[1] = "Scarab", 
[4] = "Jelly_Explode", 
[5] = "Beetle", 
["island"] = 2 
}, 
[4] = { 
[6] = "Centipede", 
[2] = "Firefly", 
[3] = "Scorpion", 
[1] = "Scarab", 
[4] = "Jelly_Regen", 
[5] = "Burrower", 
["island"] = 4 
}, 
[3] = { 
[6] = "Digger", 
[2] = "Scarab", 
[3] = "Hornet", 
[1] = "Leaper", 
[4] = "Jelly_Armor", 
[5] = "Beetle", 
["island"] = 3 
} 
} 
}

 

SquadData = {
["money"] = 0, ["cores"] = 0, ["bIsFavor"] = false, ["repairs"] = 0, ["CorpReward"] = {CreateEffect({weapon = "Support_Wind",}), CreateEffect({skill1 = "Regen",skill2 = "Move",pilot = "Pilot_Caretaker",}), CreateEffect({power = 2,}), },
["RewardClaimed"] = true, 
["skip_pawns"] = true, 

["storage_size"] = 3, ["CorpStore"] = {CreateEffect({weapon = "Support_Waterdrill",money = -2,}), CreateEffect({weapon = "Prime_Flamespreader",money = -2,}), CreateEffect({weapon = "Support_Missiles",money = -2,}), CreateEffect({stock = 0,}), CreateEffect({money = -3,stock = -1,cores = 1,}), CreateEffect({money = -1,power = 1,stock = -1,}), },
["island_store_count"] = 1, ["store_undo_size"] = 4, ["store_undo_0"] = {["Effect"] = CreateEffect({money = 1,power = -1,stock = -1,}), },
["store_undo_1"] = {["Effect"] = CreateEffect({money = 1,power = -1,stock = -1,}), },
["store_undo_2"] = {["Effect"] = CreateEffect({money = 1,power = -1,stock = -1,}), },
["store_undo_3"] = {["Effect"] = CreateEffect({money = 1,power = -1,stock = -1,}), },
}
 

