{
  "CardGameData": {
    "StartMapModel": {
      "mapLevel": 0,
      "Width": 0,
      "NodeColumns": [],
      "ChosenPath": [],
      "UnlockableCardIds": [],
      "Id": "fe699c2f-ea66-4959-8ccc-05a2d6cb9934"
    },
    "CurrentMapModel": {
      "mapLevel": 0,
      "Width": 0,
      "NodeColumns": [],
      "ChosenPath": [],
      "UnlockableCardIds": [],
      "Id": "9bdb1922-0f2a-4193-8de7-624d7be88467"
    },
    "CurrentExecutingNode": {
      "NodeType": 0,
      "ExtraNodeName": 0,
      "Components": [],
      "NextNodePaths": [],
      "Position": {
        "x": 0,
        "y": 0,
        "magnitude": 0.0,
        "sqrMagnitude": 0
      },
      "Name": "",
      "DebugMessage": "",
      "messageBoxID": "0",
      "Id": "8f86ccf0-8662-453d-9d84-48836796c60a"
    },
    "PlayerData": {
      "MaxHealth": -1,
      "CurrentHealth": -1,
      "CardDeckData": {
        "CardDatas": []
      },
      "currencyDataList": [],
      "relicIdList": [],
      "Blessings": [],
      "MaxBlessingCount": 0,
      "mapResultDataList": [],
      "stroyValue": 0
    },
    "haveCardGameSave": false,
    "chapter": 0
  },
  "UnlockData": {
    "GameUnlocks": []
  },
  "cardPackType": 0,
  "CustomDeckList": [
    {
      "Name": "1",
      "CardIds": [
        "Card_00_014",
        "Card_02_005",
        "Card_02_005",
        "Card_06_005",
        "Card_00_009",
        "Card_05_007",
        "Card_05_007",
        "Card_09_001",
        "Card_06_005",
        "Card_00_014",
        "Card_24_001",
        "Card_00_003",
        "Card_00_003",
        "Card_00_009",
        "Card_00_009"
      ],
      "Locked": false,
      "Id": "c1fbc335-682d-4432-ba65-b8cedb45efb4"
    }
  ],
  "SelectedCardDeckName": "1",
  "playerAllCardCollectionList": [
    {
      "cardID": "Card_00_001",
      "count": 0,
      "MaxCount": 10,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": true,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_003",
      "count": 10,
      "MaxCount": 10,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_005",
      "count": 0,
      "MaxCount": 10,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_007",
      "count": 6,
      "MaxCount": 6,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_008",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_009",
      "count": 4,
      "MaxCount": 4,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_010",
      "count": 0,
      "MaxCount": 6,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": true,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_011",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_012",
      "count": 0,
      "MaxCount": 6,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_013",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_014",
      "count": 6,
      "MaxCount": 6,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_015",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_016",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_017",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_00_018",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_01_001",
      "count": 0,
      "MaxCount": 6,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": true,
      "newCardTag": false
    },
    {
      "cardID": "Card_01_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_01_003",
      "count": 6,
      "MaxCount": 6,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_01_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_01_005",
      "count": 0,
      "MaxCount": 6,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_01_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_02_001",
      "count": 0,
      "MaxCount": 3,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": true,
      "newCardTag": false
    },
    {
      "cardID": "Card_02_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_02_003",
      "count": 0,
      "MaxCount": 3,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_02_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_02_005",
      "count": 3,
      "MaxCount": 3,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_02_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_001",
      "count": 6,
      "MaxCount": 6,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_003",
      "count": 0,
      "MaxCount": 6,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_005",
      "count": 0,
      "MaxCount": 6,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_007",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_008",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_03_009",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_04_001",
      "count": 0,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": true,
      "newCardTag": false
    },
    {
      "cardID": "Card_04_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_04_003",
      "count": 0,
      "MaxCount": 1,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_04_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_04_005",
      "count": 1,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_04_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_04_998",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_99_001",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_001",
      "count": 0,
      "MaxCount": 4,
      "unlocked": true,
      "AppearanceChapter": 1,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_003",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_005",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_007",
      "count": 4,
      "MaxCount": 4,
      "unlocked": true,
      "AppearanceChapter": 1,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_008",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_009",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_010",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_011",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_05_012",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_06_001",
      "count": 0,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": true,
      "newCardTag": false
    },
    {
      "cardID": "Card_06_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_06_003",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_06_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_06_005",
      "count": 2,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_06_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_07_001",
      "count": 4,
      "MaxCount": 4,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_07_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_07_003",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_07_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_07_005",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_07_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_08_001",
      "count": 0,
      "MaxCount": 3,
      "unlocked": true,
      "AppearanceChapter": 1,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_08_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_08_003",
      "count": 0,
      "MaxCount": 3,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_08_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_08_005",
      "count": 0,
      "MaxCount": 3,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_08_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_09_001",
      "count": 2,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 1,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_09_002",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_09_003",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_10_001",
      "count": 4,
      "MaxCount": 4,
      "unlocked": true,
      "AppearanceChapter": 2,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_10_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_10_003",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_10_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_10_005",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_10_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_11_001",
      "count": 0,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": true,
      "newCardTag": false
    },
    {
      "cardID": "Card_11_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_11_003",
      "count": 2,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_11_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_11_005",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_11_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_12_001",
      "count": 1,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 2,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_12_002",
      "count": 1,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 2,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_13_001",
      "count": 3,
      "MaxCount": 3,
      "unlocked": true,
      "AppearanceChapter": 2,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_13_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_13_003",
      "count": 0,
      "MaxCount": 3,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_13_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_13_005",
      "count": 0,
      "MaxCount": 3,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_13_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_14_001",
      "count": 2,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 2,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_14_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_15_001",
      "count": 0,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 1,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_15_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_15_003",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_15_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_15_005",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_15_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_16_001",
      "count": 0,
      "MaxCount": 1,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_17_001",
      "count": 2,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 3,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_17_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_18_001",
      "count": 2,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 3,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_18_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_18_003",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_18_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_18_005",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_18_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_19_001",
      "count": 1,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 3,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_19_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_20_001",
      "count": 2,
      "MaxCount": 2,
      "unlocked": true,
      "AppearanceChapter": 3,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_20_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_20_003",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_20_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_20_005",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_20_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_21_001",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_22_001",
      "count": 0,
      "MaxCount": 1,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_23_001",
      "count": 1,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 2,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_24_001",
      "count": 1,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 2,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_25_001",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_26_001",
      "count": 1,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 3,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_26_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_98_001",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 0,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_27_001",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_27_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_28_001",
      "count": 0,
      "MaxCount": 5,
      "unlocked": false,
      "AppearanceChapter": 4,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_28_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_28_003",
      "count": 0,
      "MaxCount": 5,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_28_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_28_005",
      "count": 0,
      "MaxCount": 5,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_28_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_29_001",
      "count": 1,
      "MaxCount": 1,
      "unlocked": true,
      "AppearanceChapter": 3,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_30_001",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_30_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_30_003",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_30_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_30_005",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_30_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_31_001",
      "count": 0,
      "MaxCount": 4,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_31_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_32_001",
      "count": 0,
      "MaxCount": 3,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_32_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_32_003",
      "count": 0,
      "MaxCount": 3,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_32_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_32_005",
      "count": 0,
      "MaxCount": 3,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_32_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_33_001",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_33_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_33_003",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_33_004",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_33_005",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_33_006",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_34_001",
      "count": 0,
      "MaxCount": 2,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_101_001",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_101_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_102_001",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_102_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_103_001",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_104_001",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_104_002",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    },
    {
      "cardID": "Card_105_001",
      "count": 0,
      "MaxCount": 0,
      "unlocked": false,
      "AppearanceChapter": 99,
      "IsAlienation": false,
      "newCardTag": false
    }
  ],
  "currentProgress": 4,
  "currentChapter": 18,
  "lastUpdated": -8584380246123007063,
  "currencyDataList": [
    {
      "currencyType": 2,
      "Amount": 614
    },
    {
      "currencyType": 3,
      "Amount": 5
    },
    {
      "currencyType": 1,
      "Amount": 587
    }
  ],
  "prisonEvent": [
    "第一章_01_06",
    "第二章_02_09",
    "第三章_03_01",
    "第三章_03_04"
  ],
  "MainEquipRelic": [],
  "SubEquipRelic": [
    2017,
    2013,
    2015,
    2018
  ],
  "playStartAnimation": false,
  "fastBattle": true,
  "shopRemind": false,
  "deckRemind": false,
  "newCardRemind": true,
  "skipShopAnimation": true,
  "achievementData": {
    "unlockCardCount": 10,
    "hManCount": 0,
    "fullHPPassCount": 2,
    "levelUpCardCount": 10,
    "leveUpRelicCount": 3,
    "lossCount": 0,
    "modifiedCardCount": 7,
    "damageGreater300": false,
    "slimeHCGActive": true,
    "defeatInstructor": true,
    "defeatDoctor": true,
    "defeatTentacle": true,
    "defeatFinalBoss": true,
    "completeChapter1": true,
    "limeHCGActive": true,
    "goodEnd": false,
    "normalEnd": false,
    "badEnd": false
  },
  "storyValueChange": 1
}